from __future__ import annotations

# Compatibility surface for existing organ imports. The canonical scanner is shared
# because Brain, memory, and credential foundation must apply the same firewall.
from sentinel.shared.safety_scanner import (
    DOWNSTREAM_DANGEROUS_FORBIDDEN_KEYS,
    OrganSafetyScanCategory,
    OrganSafetyScanResult,
    SHARED_AUTHORITY_EXPANSION_KEYS,
    SHARED_BROWSER_DANGEROUS_KEYS,
    SHARED_CREDENTIAL_DANGEROUS_KEYS,
    SHARED_EXTERNAL_ACTION_KEYS,
    SHARED_FORBIDDEN_SECRET_KEYS,
    SHARED_NEGATIVE_CONTROL_SAFE_KEYS,
    SHARED_PROVIDER_OVERRIDE_KEYS,
    SHARED_RUNTIME_FORBIDDEN_KEYS,
    SHARED_RUNTIME_FORBIDDEN_TEXT,
    SHARED_SECRET_LIKE_PATTERN,
    dedupe_scan_findings,
    merge_scan_results,
    parse_authority_bool,
    parse_evidence_bool,
    scan_forbidden_external_surfaces,
    scan_forbidden_payload_categorized,
    scan_forbidden_payload_flat,
    scan_provider_override,
    scan_secret_like_text,
)

__all__ = [
    "DOWNSTREAM_DANGEROUS_FORBIDDEN_KEYS",
    "OrganSafetyScanCategory",
    "OrganSafetyScanResult",
    "SHARED_AUTHORITY_EXPANSION_KEYS",
    "SHARED_BROWSER_DANGEROUS_KEYS",
    "SHARED_CREDENTIAL_DANGEROUS_KEYS",
    "SHARED_EXTERNAL_ACTION_KEYS",
    "SHARED_FORBIDDEN_SECRET_KEYS",
    "SHARED_NEGATIVE_CONTROL_SAFE_KEYS",
    "SHARED_PROVIDER_OVERRIDE_KEYS",
    "SHARED_RUNTIME_FORBIDDEN_KEYS",
    "SHARED_RUNTIME_FORBIDDEN_TEXT",
    "SHARED_SECRET_LIKE_PATTERN",
    "dedupe_scan_findings",
    "merge_scan_results",
    "parse_authority_bool",
    "parse_evidence_bool",
    "scan_forbidden_external_surfaces",
    "scan_forbidden_payload_categorized",
    "scan_forbidden_payload_flat",
    "scan_provider_override",
    "scan_secret_like_text",
]
