"""Backward-compatibility shim — real module lives at
:mod:`sentinel.organs.browser.v3_advanced_authorities`.

Task 5.2 / Wave D3 (Browser Legacy Consolidation).
"""

from __future__ import annotations

from sentinel.organs.browser.v3_advanced_authorities import (  # noqa: F401
    BrowserCookieStorageBackend,
    BrowserCookieStorageBackendResult,
    BrowserCookieStorageContractExecutor,
    BrowserCookieStorageContractReceipt,
    BrowserCookieStorageContractRequest,
    BrowserCookieStorageContractResult,
    BrowserHarBodyCaptureBackend,
    BrowserHarBodyCaptureBackendResult,
    BrowserHarBodyCaptureExecutor,
    BrowserHarBodyCaptureReceipt,
    BrowserHarBodyCaptureRequest,
    BrowserHarBodyCaptureResult,
    BrowserJsEvaluateBackend,
    BrowserJsEvaluateBackendResult,
    BrowserJsEvaluateSandboxedExecutor,
    BrowserJsEvaluateSandboxedReceipt,
    BrowserJsEvaluateSandboxedRequest,
    BrowserJsEvaluateSandboxedResult,
    BrowserLoginAuthorityExecutor,
    BrowserLoginAuthorityReceipt,
    BrowserLoginAuthorityRequest,
    BrowserLoginAuthorityResult,
    BrowserLoginBackend,
    BrowserLoginBackendResult,
    BrowserPrivateSessionBackend,
    BrowserPrivateSessionBackendResult,
    BrowserPrivateSessionExecutor,
    BrowserPrivateSessionReceipt,
    BrowserPrivateSessionRequest,
    BrowserPrivateSessionResult,
)

__all__ = [
    "BrowserCookieStorageBackend",
    "BrowserCookieStorageBackendResult",
    "BrowserCookieStorageContractExecutor",
    "BrowserCookieStorageContractReceipt",
    "BrowserCookieStorageContractRequest",
    "BrowserCookieStorageContractResult",
    "BrowserHarBodyCaptureBackend",
    "BrowserHarBodyCaptureBackendResult",
    "BrowserHarBodyCaptureExecutor",
    "BrowserHarBodyCaptureReceipt",
    "BrowserHarBodyCaptureRequest",
    "BrowserHarBodyCaptureResult",
    "BrowserJsEvaluateBackend",
    "BrowserJsEvaluateBackendResult",
    "BrowserJsEvaluateSandboxedExecutor",
    "BrowserJsEvaluateSandboxedReceipt",
    "BrowserJsEvaluateSandboxedRequest",
    "BrowserJsEvaluateSandboxedResult",
    "BrowserLoginAuthorityExecutor",
    "BrowserLoginAuthorityReceipt",
    "BrowserLoginAuthorityRequest",
    "BrowserLoginAuthorityResult",
    "BrowserLoginBackend",
    "BrowserLoginBackendResult",
    "BrowserPrivateSessionBackend",
    "BrowserPrivateSessionBackendResult",
    "BrowserPrivateSessionExecutor",
    "BrowserPrivateSessionReceipt",
    "BrowserPrivateSessionRequest",
    "BrowserPrivateSessionResult",
]
